# Generated by Django 5.0.7 on 2024-07-22 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='turma',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='turma',
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='periodo_historico',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='periodo_historico',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='periodo_historico',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.professor'),
        ),
        migrations.AddField(
            model_name='professor',
            name='disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.disciplina'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='datanasc',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.disciplina'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='detalhamento',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='periodo_historico',
            name='detalhamento',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='periodo_historico',
            name='topico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.topico'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='topico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.topico'),
        ),
        migrations.AlterField(
            model_name='topico',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Turma',
        ),
    ]
