# Generated by Django 5.0.7 on 2024-07-22 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_periodo_historico_detalhamento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodo_historico',
            old_name='impactos',
            new_name='impactos_e_consequencias',
        ),
        migrations.RenameField(
            model_name='periodo_historico',
            old_name='seculo',
            new_name='periodo',
        ),
    ]
